<a href="https://colab.research.google.com/github/SoumyaR01/lead_scoring_18Dec2023/blob/main/Language_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install git+https://github.com/speechbrain/speechbrain.git@develop

  Cloning https://github.com/speechbrain/speechbrain.git (to revision develop) to /tmp/pip-req-build-bjc9zs6z
  Running command git clone --filter=blob:none --quiet https://github.com/speechbrain/speechbrain.git /tmp/pip-req-build-bjc9zs6z
  Resolved https://github.com/speechbrain/speechbrain.git to commit b18646d80c7d5081a99a32f2a3e44cebe2a8249f
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.9/116.9 kB 9.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 722.2/722.2 kB 36.7 MB/s eta 0:00:00
  Created wheel for speechbrain: filename=speechbrain-1.0.2-py3-none-any.whl size=844844 sha256=924cba63dfe1c3049cc9d00df7692eebafb82b8e170b3eebe6927c82fa0c8c22
  Stored in directory: /tmp/pip-ephem-wheel-cache-06gwfxqv/wheels/e1/a5/ca/79fbb0a28f6f392850cfd5bac6a4dcec0f10a7e49d4c1e87cb
Successfully built speechbrain


In [2]:
import torch
print(torch.cuda.is_available())  # Prints True if CUDA is available
print(torch.cuda.device_count()) # Prints the number of CUDA-enabled GPUs

True
1


In [4]:
!nvidia-smi

Thu Jan  2 06:33:25 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   60C    P8              10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [5]:
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

Looking in indexes: https://download.pytorch.org/whl/cu118


In [6]:
import torch
print(torch.cuda.is_available())
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))



True
Tesla T4


In [9]:
import torchaudio
from speechbrain.inference.classifiers import EncoderClassifier
import os
import time

In [15]:
# prompt: convert mp3 to wav

!pip install pydub

from pydub import AudioSegment

def convert_mp3_to_wav(input_file, output_file):
    """Converts an MP3 file to WAV format.

    Args:
        input_file: Path to the input MP3 file.
        output_file: Path to the output WAV file.
    """
    try:
        sound = AudioSegment.from_mp3(input_file)
        sound.export(output_file, format="wav")
        print(f"Successfully converted {input_file} to {output_file}")
    except FileNotFoundError:
        print(f"Error: Input file '{input_file}' not found.")
    except Exception as e:
        print(f"An error occurred: {e}")

# Example usage
# Replace 'input.mp3' and 'output.wav' with your actual file paths
input_mp3_file = '/content/Sudha Murty Speech.mp3'
output_wav_file = '/content/outputwav.wav'
convert_mp3_to_wav(input_mp3_file, output_wav_file)

Successfully converted /content/Sudha Murty Speech.mp3 to /content/outputwav.wav


In [20]:
import torchaudio
from speechbrain.inference.classifiers import EncoderClassifier
import os
# torchaudio.set_audio_backend("sox_io")
# os.environ["CUDA_VISIBLE_DEVICES"] = "1"

# Change the source to the directory containing hyperparams.yaml
classifier = EncoderClassifier.from_hparams(
    source="/content/",
    hparams_file="hyperparams.yaml",
    run_opts={"device": "cuda:0"}  # Changed to cuda:0
)


audio_path = "/content/Sayani Ghosh Bengali.wav"

if not os.path.exists(audio_path):
    raise FileNotFoundError(f"File not found: {audio_path}")


signal = classifier.load_audio(audio_path)
prediction = classifier.classify_batch(signal)

print(prediction)
print(prediction[1].exp())
print(prediction[3])

(tensor([[-2.9266e+01, -2.4988e+01, -2.6575e+01, -2.2365e+01, -5.8433e+00,
         -2.6655e+01, -3.0108e+01, -2.5232e+01, -2.8422e+01, -2.9108e-03,
         -2.7455e+01, -2.6004e+01, -2.4815e+01, -2.4079e+01, -2.5300e+01,
         -2.3880e+01, -2.4394e+01, -2.5196e+01, -2.3488e+01, -2.0692e+01,
         -2.4699e+01, -2.2420e+01, -2.6062e+01, -2.3627e+01, -2.6092e+01,
         -2.1675e+01, -2.6345e+01, -2.6434e+01, -2.1391e+01, -2.1494e+01,
         -2.8049e+01, -1.3759e+01, -3.2954e+01, -2.6627e+01, -2.7494e+01,
         -1.3248e+01, -2.4684e+01, -2.1614e+01, -2.1818e+01, -1.5019e+01,
         -2.6747e+01, -2.9885e+01, -2.5911e+01, -2.3761e+01, -2.5837e+01,
         -2.2863e+01, -2.9398e+01, -1.7744e+01, -2.8417e+01, -2.9928e+01,
         -1.8485e+01, -2.2452e+01, -2.5464e+01, -2.2089e+01, -2.1588e+01,
         -3.0064e+01, -2.8822e+01, -2.8466e+01, -2.7403e+01, -2.6876e+01,
         -1.9744e+01, -1.8015e+01, -2.6356e+01, -1.2516e+01, -2.3329e+01,
         -2.1904e+01, -2.6809e+01, -1

In [21]:
import torchaudio
from speechbrain.inference.classifiers import EncoderClassifier
import os
# torchaudio.set_audio_backend("sox_io")
# os.environ["CUDA_VISIBLE_DEVICES"] = "1"

# Change the source to the directory containing hyperparams.yaml
classifier = EncoderClassifier.from_hparams(
    source="/content/",
    hparams_file="hyperparams.yaml",
    run_opts={"device": "cuda:0"}  # Changed to cuda:0
)


audio_path = "/content/Sudha Murty English.wav"

if not os.path.exists(audio_path):
    raise FileNotFoundError(f"File not found: {audio_path}")


signal = classifier.load_audio(audio_path)
prediction = classifier.classify_batch(signal)

print(prediction)
print(prediction[1].exp())
print(prediction[3])

(tensor([[-12.2467,  -3.9077,  -7.4878,  -3.8609,  -7.2566, -10.1617,  -7.8436,
          -9.5382,  -8.9792,  -7.2856, -11.3262, -10.6836,  -8.6989,  -7.2921,
          -9.5089, -13.8012,  -5.1397,  -8.6077,  -8.0213,  -7.5331,  -6.0541,
         -10.6342, -11.9700, -10.8149, -13.2298,  -8.9459,  -9.7703,  -5.7927,
         -11.0792,  -8.7832, -15.5610,  -6.0382, -10.8671,  -6.1598,  -9.2993,
          -1.0503,  -8.3590, -12.6897,  -8.4480,  -6.8315, -10.9436,  -8.3645,
          -8.0487,  -9.9502,  -9.7200, -14.7816, -12.5785, -11.3673,  -9.7697,
         -14.1414,  -3.7042, -10.6240, -11.3995,  -7.7551, -10.3771, -14.4184,
          -9.0391,  -9.9566, -10.0598,  -8.6062,  -4.3148,  -3.1108,  -7.0956,
          -3.7086,  -4.9748,  -3.5449, -14.6242,  -6.5242,  -7.4511,  -5.3633,
          -7.2813,  -7.6801,  -3.5711,  -9.5607,  -3.8375,  -9.5320,  -6.4842,
         -14.0627, -10.2554,  -5.7280,  -3.2570,  -8.4552, -13.0350,  -4.6312,
          -6.4282,  -6.3844,  -7.4901,  -6.2907,  -

In [23]:
import torchaudio
from speechbrain.inference.classifiers import EncoderClassifier
import os
# torchaudio.set_audio_backend("sox_io")
# os.environ["CUDA_VISIBLE_DEVICES"] = "1"

# Change the source to the directory containing hyperparams.yaml
classifier = EncoderClassifier.from_hparams(
    source="/content/",
    hparams_file="hyperparams.yaml",
    run_opts={"device": "cuda:0"}  # Changed to cuda:0
)


audio_path = "/content/Punjabi.wav"

if not os.path.exists(audio_path):
    raise FileNotFoundError(f"File not found: {audio_path}")


signal = classifier.load_audio(audio_path)
prediction = classifier.classify_batch(signal)

print(prediction)
print(prediction[1].exp())
print(prediction[3])

(tensor([[-27.3148, -23.8845, -19.6518, -18.0312, -16.4431, -24.8118, -24.7435,
         -25.7743, -28.0193, -17.5630, -21.8667, -28.5687, -23.6085, -19.8313,
         -20.8006, -26.8281, -19.6168, -23.6418, -23.3828, -22.4028, -23.8812,
         -23.0667, -27.0693, -25.3674, -24.9755, -21.6191, -23.8411, -25.1845,
         -24.3548, -24.7537, -31.2314,  -8.6525, -27.9382, -22.2096, -21.0233,
          -1.6791, -26.3546, -26.6237, -22.6808, -12.1557, -24.7824, -26.4318,
         -22.4202, -26.1772, -20.4481, -27.8513, -27.4562, -21.2976, -26.6239,
         -23.9387, -10.8846, -25.4061, -28.8563, -25.1358, -24.9674, -24.9666,
         -28.8663, -24.6703, -24.9980, -23.3967, -19.5654, -14.0568, -22.4795,
         -10.8681, -21.7795, -17.5549, -24.4232, -15.6051, -27.0431, -18.4874,
         -20.8441, -22.0133,  -0.2812, -24.8321, -12.9344, -25.6489, -20.4809,
         -30.9301, -11.3593, -16.0593,  -4.1864, -19.6829, -24.9659, -21.0669,
         -26.9975, -22.1479, -20.3820, -23.1179, -2

In [24]:
import torchaudio
from speechbrain.inference.classifiers import EncoderClassifier
import os
# torchaudio.set_audio_backend("sox_io")
# os.environ["CUDA_VISIBLE_DEVICES"] = "1"

# Change the source to the directory containing hyperparams.yaml
classifier = EncoderClassifier.from_hparams(
    source="/content/",
    hparams_file="hyperparams.yaml",
    run_opts={"device": "cuda:0"}  # Changed to cuda:0
)


audio_path = "/content/Tamil.wav"

if not os.path.exists(audio_path):
    raise FileNotFoundError(f"File not found: {audio_path}")


signal = classifier.load_audio(audio_path)
prediction = classifier.classify_batch(signal)

print(prediction)
print(prediction[1].exp())
print(prediction[3])

(tensor([[-3.5366e+01, -2.1369e+01, -1.7227e+01, -2.4827e+01, -1.4586e+01,
         -2.9319e+01, -3.1313e+01, -2.7192e+01, -2.7389e+01, -1.6335e+01,
         -2.6579e+01, -2.8878e+01, -2.8719e+01, -1.9552e+01, -2.3208e+01,
         -2.3613e+01, -2.1877e+01, -2.6793e+01, -2.6714e+01, -2.5992e+01,
         -2.2331e+01, -2.9785e+01, -2.1337e+01, -2.4752e+01, -2.4295e+01,
         -2.9575e+01, -2.6687e+01, -2.9471e+01, -2.8772e+01, -2.5046e+01,
         -2.7686e+01, -1.7306e+01, -3.1682e+01, -2.2858e+01, -2.1909e+01,
         -1.1975e+01, -2.6658e+01, -2.7165e+01, -2.7823e+01, -2.4250e+01,
         -2.9039e+01, -1.9641e+01, -2.5252e+01, -2.5959e+01, -2.8131e+01,
         -2.8512e+01, -1.8970e+01, -2.6578e+01, -2.6875e+01, -2.5049e+01,
         -7.7275e+00, -2.1165e+01, -2.1425e+01, -2.8476e+01, -2.6836e+01,
         -2.9353e+01, -2.6973e+01, -2.8474e+01, -2.4267e+01, -2.6443e+01,
         -2.7589e+01, -6.3569e+00, -2.3885e+01, -1.2532e+01, -2.2031e+01,
         -2.4794e+01, -2.5329e+01, -1

In [25]:
import torchaudio
from speechbrain.inference.classifiers import EncoderClassifier
import os
# torchaudio.set_audio_backend("sox_io")
# os.environ["CUDA_VISIBLE_DEVICES"] = "1"

# Change the source to the directory containing hyperparams.yaml
classifier = EncoderClassifier.from_hparams(
    source="/content/",
    hparams_file="hyperparams.yaml",
    run_opts={"device": "cuda:0"}  # Changed to cuda:0
)


audio_path = "/content/Gujurati.wav"

if not os.path.exists(audio_path):
    raise FileNotFoundError(f"File not found: {audio_path}")


signal = classifier.load_audio(audio_path)
prediction = classifier.classify_batch(signal)

print(prediction)
print(prediction[1].exp())
print(prediction[3])

(tensor([[-21.4242, -13.9790, -14.0013, -12.5085, -12.6248, -22.9896, -17.7530,
         -17.1227, -15.9427, -13.1963, -17.7214, -18.1771, -14.5632, -10.9548,
         -13.9965, -18.4770, -18.7569, -19.6408, -19.4436, -14.3541, -18.5392,
         -17.9366, -16.7948, -19.4782, -18.9892, -17.6394, -22.5440, -19.0168,
         -17.6760, -18.5628, -22.0794,  -0.1716, -23.5776, -11.5298, -14.6788,
          -2.1393, -18.0739, -17.2550, -20.0234, -12.9804, -20.1613, -14.0058,
         -18.2765, -19.4510, -17.5061, -20.6278, -15.0249, -18.3528, -17.7624,
         -15.3015,  -9.2064, -20.5530, -19.4792, -19.8507, -13.6337, -18.1789,
         -18.6549, -20.4408, -14.7577, -20.8721, -11.4729, -14.4745, -17.2665,
          -3.5015, -12.5691, -14.7138, -19.1441, -13.0861, -17.9956, -19.7032,
         -19.2643, -14.2029,  -8.8719, -16.6406,  -9.6125, -17.8349, -12.9703,
         -22.2400, -10.4364, -15.7752,  -4.7323, -12.7035, -16.6510, -12.3908,
         -17.9066, -14.5344, -17.8908, -17.0876, -1

In [26]:
import torchaudio
from speechbrain.inference.classifiers import EncoderClassifier
import os
# torchaudio.set_audio_backend("sox_io")
# os.environ["CUDA_VISIBLE_DEVICES"] = "1"

# Change the source to the directory containing hyperparams.yaml
classifier = EncoderClassifier.from_hparams(
    source="/content/",
    hparams_file="hyperparams.yaml",
    run_opts={"device": "cuda:0"}  # Changed to cuda:0
)


audio_path = "/content/Telugu.wav"

if not os.path.exists(audio_path):
    raise FileNotFoundError(f"File not found: {audio_path}")


signal = classifier.load_audio(audio_path)
prediction = classifier.classify_batch(signal)

print(prediction)
print(prediction[1].exp())
print(prediction[3])

(tensor([[-22.9878, -15.2069,  -9.8938, -10.4453,  -8.5811, -18.6481, -11.3497,
         -13.4263, -14.6886, -10.2410, -14.4296, -18.3593, -11.3153, -11.9840,
         -13.8621, -15.1595, -18.2111, -16.8179, -17.2613,  -8.1977, -15.8590,
         -18.7139, -14.8401, -18.9520, -16.0306, -17.8045, -14.4275, -19.1396,
         -17.4278, -12.9963, -17.5289,  -6.0711, -22.2126, -11.2234, -15.7740,
          -4.1817, -11.6828, -14.5721, -14.6705, -15.3308, -18.5367, -16.1911,
         -14.0460, -13.4053, -14.4340, -12.5940, -14.0822, -15.3139, -12.1449,
         -21.4039,  -0.7935, -16.3003, -20.6341, -18.5174, -13.2415, -16.6803,
         -14.6211, -17.0358, -16.3971, -17.8870,  -8.8133,  -6.7945, -15.8481,
          -5.5971, -11.0946, -14.0577, -17.0333, -13.1530, -19.7460, -21.6040,
         -20.5024, -17.2443,  -9.0492, -11.6963,  -4.3769, -17.1159, -10.9780,
         -14.5553, -13.6017, -15.9792,  -5.4648,  -7.6595, -17.1496, -10.7930,
         -18.0934, -12.1389, -12.7314, -13.2043, -1

In [28]:
import torchaudio
from speechbrain.inference.classifiers import EncoderClassifier
import os
# torchaudio.set_audio_backend("sox_io")
# os.environ["CUDA_VISIBLE_DEVICES"] = "1"

# Change the source to the directory containing hyperparams.yaml
classifier = EncoderClassifier.from_hparams(
    source="/content/",
    hparams_file="hyperparams.yaml",
    run_opts={"device": "cuda:0"}  # Changed to cuda:0
)


audio_path = "/content/Marathi.wav"

if not os.path.exists(audio_path):
    raise FileNotFoundError(f"File not found: {audio_path}")


signal = classifier.load_audio(audio_path)
prediction = classifier.classify_batch(signal)

print(prediction)
print(prediction[1].exp())
print(prediction[3])

(tensor([[-21.1757, -13.8872, -13.8583, -10.5370,  -9.0707, -17.2636, -17.6157,
         -18.3194, -16.6353, -11.3035, -17.0193, -17.9981, -16.9382, -11.1743,
         -20.5130, -17.4338, -17.5707, -16.7094, -19.4866, -12.1118, -14.2781,
         -17.8332, -14.9716, -17.3388, -16.5691, -15.7920, -19.9277, -16.9722,
         -13.3260, -15.5844, -20.6016,  -4.8034, -24.8886, -13.3427, -17.8578,
          -1.5135, -16.9093, -19.1766, -15.7550, -10.9727, -24.1737, -15.3048,
         -16.1370, -16.7920, -16.6707, -14.4717, -16.8941, -15.8112, -17.3805,
         -16.9509,  -8.0503, -15.1691, -18.7809, -15.8769, -13.7911, -18.1174,
         -17.1223, -18.7983, -18.4651, -21.2981, -15.2197,  -9.2162, -16.1868,
          -0.2658, -13.8805, -10.8662, -16.7348, -13.9934, -19.3703, -16.7174,
         -16.2040, -13.1827,  -7.4918, -16.0577, -10.7445, -15.7174, -11.8977,
         -22.2081,  -9.2085, -21.0096,  -6.1040, -11.1553, -17.7142, -12.3263,
         -20.1392, -17.5367, -14.6628, -15.3336, -1

In [29]:
import torchaudio
from speechbrain.inference.classifiers import EncoderClassifier
import os
# torchaudio.set_audio_backend("sox_io")
# os.environ["CUDA_VISIBLE_DEVICES"] = "1"

# Change the source to the directory containing hyperparams.yaml
classifier = EncoderClassifier.from_hparams(
    source="/content/",
    hparams_file="hyperparams.yaml",
    run_opts={"device": "cuda:0"}  # Changed to cuda:0
)


audio_path = "/content/French.wav"

if not os.path.exists(audio_path):
    raise FileNotFoundError(f"File not found: {audio_path}")


signal = classifier.load_audio(audio_path)
prediction = classifier.classify_batch(signal)

print(prediction)
print(prediction[1].exp())
print(prediction[3])

(tensor([[-10.8627,  -9.8119,  -9.6040, -10.0181,  -6.6038,  -2.0602, -10.8816,
          -8.3746,  -8.9410,  -7.1394,  -6.7198,  -8.8754,  -9.5948,  -8.2151,
         -11.0126,  -6.7327, -11.1514,  -9.7260,  -8.4554,  -6.2228,  -5.0956,
          -6.9600,  -7.2739,  -8.8841,  -8.8215,  -3.4635,  -9.3441,  -2.0675,
          -4.9519, -11.8042, -10.3657,  -6.4364,  -4.6356,  -9.0869,  -7.2703,
          -6.6285, -11.0741,  -2.8320,  -8.2831,  -7.4016,  -9.5247,  -9.2536,
         -10.5973,  -8.1337, -10.6132,  -8.7735,  -8.3872,  -7.7170,  -6.1702,
         -13.2582,  -7.3064,  -8.4767,  -8.4783,  -7.3006,  -3.1536, -14.2126,
         -10.2820, -13.6927,  -5.5197,  -9.8282,  -6.1733,  -7.6939,  -7.9631,
          -9.4813,  -5.3856, -15.8328,  -9.7093, -11.8308,  -5.9515,  -4.2476,
          -5.5339,  -9.3872, -10.5903,  -3.9020,  -9.7142,  -5.7210,  -6.6274,
         -12.6174,  -8.1599, -10.4421,  -7.7664, -12.5376,  -1.7607,  -7.5397,
          -6.4727,  -8.8703,  -3.3585,  -8.2518, -1

In [30]:
import torchaudio
from speechbrain.inference.classifiers import EncoderClassifier
import os
# torchaudio.set_audio_backend("sox_io")
# os.environ["CUDA_VISIBLE_DEVICES"] = "1"

# Change the source to the directory containing hyperparams.yaml
classifier = EncoderClassifier.from_hparams(
    source="/content/",
    hparams_file="hyperparams.yaml",
    run_opts={"device": "cuda:0"}  # Changed to cuda:0
)


audio_path = "/content/French.wav"

if not os.path.exists(audio_path):
    raise FileNotFoundError(f"File not found: {audio_path}")


signal = classifier.load_audio(audio_path)
prediction = classifier.classify_batch(signal)

print(prediction)
print(prediction[1].exp())
print(prediction[3])

(tensor([[-2.0024e+01, -1.7835e+01, -1.8596e+01, -1.0728e+01, -1.7604e+01,
         -1.8128e+01, -1.9697e+01, -1.5110e+01, -1.6630e+01, -1.8990e+01,
         -2.0353e+01, -6.5291e+00, -1.9740e+01, -1.3757e+01, -1.8656e+01,
         -1.4363e+01, -1.3049e+01, -1.2641e+01, -1.6052e+01, -1.2347e+01,
         -1.4738e+01, -1.4626e+01, -1.6341e+01, -1.5920e+01, -1.8828e+01,
         -1.7313e+01, -1.7489e+01, -1.3185e+01, -2.4189e-03, -1.5560e+01,
         -2.0597e+01, -2.2815e+01, -1.6762e+01, -1.5356e+01, -2.2226e+01,
         -1.6596e+01, -1.9696e+01, -1.3200e+01, -1.7153e+01, -1.6257e+01,
         -2.0826e+01, -1.7143e+01, -1.7312e+01, -1.8476e+01, -1.5399e+01,
         -1.5940e+01, -1.8539e+01, -2.0363e+01, -1.8187e+01, -2.0098e+01,
         -2.2053e+01, -1.7083e+01, -1.3348e+01, -9.6430e+00, -9.7846e+00,
         -2.3275e+01, -1.4033e+01, -2.1117e+01, -1.4215e+01, -1.8671e+01,
         -1.6658e+01, -2.3165e+01, -2.0970e+01, -2.0873e+01, -1.7785e+01,
         -1.1570e+01, -2.3535e+01, -2

In [31]:
import torchaudio
from speechbrain.inference.classifiers import EncoderClassifier
import os
# torchaudio.set_audio_backend("sox_io")
# os.environ["CUDA_VISIBLE_DEVICES"] = "1"

# Change the source to the directory containing hyperparams.yaml
classifier = EncoderClassifier.from_hparams(
    source="/content/",
    hparams_file="hyperparams.yaml",
    run_opts={"device": "cuda:0"}  # Changed to cuda:0
)


audio_path = "/content/Arabic.wav"

if not os.path.exists(audio_path):
    raise FileNotFoundError(f"File not found: {audio_path}")


signal = classifier.load_audio(audio_path)
prediction = classifier.classify_batch(signal)

print(prediction)
print(prediction[1].exp())
print(prediction[3])

(tensor([[-1.6470e+01, -1.7433e+01, -7.4484e+00, -1.0241e-02, -1.6380e+01,
         -1.3923e+01, -1.2126e+01, -1.5590e+01, -1.7882e+01, -9.8756e+00,
         -1.7941e+01, -1.8131e+01, -1.0188e+01, -1.5671e+01, -1.8281e+01,
         -1.9543e+01, -1.5441e+01, -1.3736e+01, -1.4894e+01, -1.3723e+01,
         -1.7686e+01, -1.8414e+01, -1.4328e+01, -1.8792e+01, -1.6516e+01,
         -9.5875e+00, -1.5842e+01, -1.2686e+01, -1.5154e+01, -1.5164e+01,
         -2.0282e+01, -1.6072e+01, -1.8731e+01, -6.4608e+00, -1.6100e+01,
         -1.1547e+01, -1.7598e+01, -1.9512e+01, -1.4661e+01, -1.4960e+01,
         -1.6892e+01, -1.7397e+01, -1.4761e+01, -1.5396e+01, -1.1044e+01,
         -1.7054e+01, -1.6064e+01, -1.8064e+01, -1.2231e+01, -1.7570e+01,
         -1.1155e+01, -1.7905e+01, -2.3494e+01, -1.7836e+01, -1.8991e+01,
         -1.6971e+01, -1.5622e+01, -1.7733e+01, -1.8241e+01, -2.0138e+01,
         -1.2897e+01, -9.4338e+00, -1.7605e+01, -1.4759e+01, -1.0349e+01,
         -6.3593e+00, -1.7102e+01, -1

In [32]:
import torchaudio
from speechbrain.inference.classifiers import EncoderClassifier
import os
# torchaudio.set_audio_backend("sox_io")
# os.environ["CUDA_VISIBLE_DEVICES"] = "1"

# Change the source to the directory containing hyperparams.yaml
classifier = EncoderClassifier.from_hparams(
    source="/content/",
    hparams_file="hyperparams.yaml",
    run_opts={"device": "cuda:0"}  # Changed to cuda:0
)


audio_path = "/content/Tibetan.wav"

if not os.path.exists(audio_path):
    raise FileNotFoundError(f"File not found: {audio_path}")


signal = classifier.load_audio(audio_path)
prediction = classifier.classify_batch(signal)

print(prediction)
print(prediction[1].exp())
print(prediction[3])

(tensor([[-14.8948, -17.9096, -14.0768, -11.9924,  -7.5222,  -8.6214, -16.7444,
         -14.7388, -15.7302,  -8.9541,  -0.3925, -14.9657, -13.6783, -16.2974,
         -13.4472, -17.0240, -10.8722,  -9.4914, -11.9939, -11.0720,  -8.8322,
         -10.1525, -15.0398, -12.8695, -17.8728,  -8.8429, -12.1554, -11.3322,
          -9.8458, -17.3760, -17.7311, -12.5920, -10.7497,  -7.8599, -13.7835,
          -6.0500, -15.9578, -12.2855, -11.9651,  -9.4562, -17.5583, -16.4223,
         -12.9821, -15.1422, -13.9128,  -8.4730, -17.2929, -14.0434, -12.8290,
         -12.2412,  -9.2998,  -4.2993, -13.2596,  -8.4933, -16.8833, -12.3996,
         -14.6142, -18.2877, -11.9495, -14.2613, -13.3876, -10.2177, -12.9006,
         -10.8328, -12.6277, -11.6073, -11.3584, -14.2944, -14.5414,  -9.0185,
         -10.5286, -10.0116, -12.7475, -11.6161, -11.2268, -10.8871, -12.2970,
         -17.5131, -10.1542, -12.1435, -10.9835, -11.0123, -13.7411, -13.4284,
         -12.6326, -17.9761, -15.7964, -11.6885, -1

In [35]:
import torchaudio
from speechbrain.inference.classifiers import EncoderClassifier
import os
# torchaudio.set_audio_backend("sox_io")
# os.environ["CUDA_VISIBLE_DEVICES"] = "1"

# Change the source to the directory containing hyperparams.yaml
classifier = EncoderClassifier.from_hparams(
    source="/content/",
    hparams_file="hyperparams.yaml",
    run_opts={"device": "cuda:0"}  # Changed to cuda:0
)


audio_path = "/content/Assamese.wav"

if not os.path.exists(audio_path):
    raise FileNotFoundError(f"File not found: {audio_path}")


signal = classifier.load_audio(audio_path)
prediction = classifier.classify_batch(signal)

print(prediction)
print(prediction[1].exp())
print(prediction[3])

(tensor([[-2.3388e+01, -1.2274e+01, -1.6876e+01, -1.4249e+01, -9.2821e-03,
         -1.9357e+01, -2.1150e+01, -1.7942e+01, -1.8138e+01, -4.8854e+00,
         -1.8525e+01, -1.8887e+01, -1.8007e+01, -1.5080e+01, -1.3240e+01,
         -1.8265e+01, -1.2026e+01, -1.1137e+01, -1.5459e+01, -8.9058e+00,
         -1.1002e+01, -1.8620e+01, -1.3891e+01, -1.2020e+01, -1.6927e+01,
         -1.2769e+01, -1.4409e+01, -1.4704e+01, -1.6592e+01, -1.4935e+01,
         -2.1165e+01, -1.2996e+01, -1.7363e+01, -1.2800e+01, -1.4689e+01,
         -9.3600e+00, -1.6701e+01, -1.3214e+01, -1.7116e+01, -1.5238e+01,
         -2.0569e+01, -1.1687e+01, -1.2748e+01, -1.4011e+01, -1.4327e+01,
         -1.6471e+01, -1.4669e+01, -1.7058e+01, -2.1219e+01, -1.9643e+01,
         -1.0378e+01, -1.2966e+01, -1.9023e+01, -1.6794e+01, -1.4192e+01,
         -1.9257e+01, -1.8090e+01, -1.9074e+01, -1.6363e+01, -1.8896e+01,
         -1.1821e+01, -1.0030e+01, -1.6883e+01, -9.7973e+00, -9.9372e+00,
         -1.3236e+01, -1.7426e+01, -1